server:
  port: 8282

euerka:
  instance:
    hostname: machine_ip

  client:
    register-with-eureka: false

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: true

zuul:
  routes:
    say-hello-api: /say-hello/**
    give-hello-api: /give-hello/**